### ISSUE TITLE
[QCR1] Autonomous Plan & Stategies

### ISSUE THREAD

**Issue by DragonDev07** [rh-robotics/19922-ITDRC#2]
- Discuss and plan out trajectories for Autonomous using [MeepMeep](https://github.com/rh-robotics/MeepMeep) and post here & on discord, *no implementation necessary*

**Comment by RZW-13** [comment]
IF: We have a way for our robot to put on clips

     Score Specimens

     Try to ascend, since it’ll be in the same place, but we can just park if we can’t figure it out

          Plan for adjustable (to avoid interfering as much as possible with the other team)

ELSE IF: We have a way for our robot to score samples in baskets

     Score samples

     Park in observation zone

          Plan for adjustable (to avoid interfering as much as possible with the other team)

ELSE:

     Park code (preferably adjustable)


Notes: 

- Adjustable paths + parking to avoid contact w/ alliance partner
- odometry!
    - We should probably advertise at our booth abt meepmeep
